### ISSUE TITLE
empty output file

### ISSUE THREAD

**Issue by rjcmarkelz** [mfcovington/extract-utr#2]
Trying to get this to work, but there is no readme :). After reading the code it seems like my gff file is not gff3 format. Is there an easy way to convert BED to GFF3? 

I followed Julin's pipeline for his tomato: 
    extract-utr.pl --gff_file=~/Sequences/ref_genomes/tomato/ITAG2.4_Chromo2.5/ITAG2.4_gene_models.gff3 \
    --genome_fa_file=~/Sequences/ref_genomes/tomato/ITAG2.4_Chromo2.5/S_lycopersicum_chromosomes.2.50.fa  \
    --cds_fa_file=~/Sequences/ref_genomes/tomato/ITAG2.4_Chromo2.5/ITAG2.4_cds.fasta  \
    --fiveprime --utr_length=1000 --gene_length=0 \
    --output_fa_file=ITAG2.4_1000bp_upstream.fa

**Comment by mfcovington** [comment]
One of the tools in GenomeTools called [gt bed_to_gff3](http://genometools.org/tools/gt_bed_to_gff3.html) should convert for you. Did it create an empty file when you used GFF2 or did it warn you that you had the wrong version of GFF file? Does your GFF have a header line w/ the version # in it?

**Comment by rjcmarkelz** [comment]
I am compiling GenomeTools right now. The GFF does not have a header. So it would not know to warn me. I will let you know how it turns out.

**Comment by rjcmarkelz** [comment]
The convertor worked, but still a blank file out the other end. 
There are scaffolds in the GFF file, could this be messing things up?

**Comment by mfcovington** [comment]
Can you post a small, yet representative, chunk of the file here?

**Comment by rjcmarkelz** [comment]
##gff-version   3
##sequence-region   Scaffold011682 4 201
##sequence-region   Scaffold011172 10 222
##sequence-region   Scaffold016924 3 158
##sequence-region   Scaffold008201 3 278
##sequence-region   Scaffold008434 2 268
##sequence-region   Scaffold005444 52 309
##sequence-region   Scaffold004310 1 450
...
A03	.	BED_feature	8794390	8797343	0	+	.	ID=BED_feature1;Name=Bra000001
A03	.	BED_block	8794390	8794534	0	+	.	Parent=BED_feature1;Name=Bra000001
A03	.	BED_thick_feature	8794511	8797095	0	+	.	Parent=BED_feature1;Name=Bra000001
A03	.	BED_block	8794622	8794805	0	+	.	Parent=BED_feature1;Name=Bra000001
A03	.	BED_block	8795258	8795339	0	+	.	Parent=BED_feature1;Name=Bra000001
A03	.	BED_block	8795431	8795535	0	+	.	Parent=BED_feature1;Name=Bra000001
A03	.	BED_block	8795634	8796021	0	+	.	Parent=BED_feature1;Name=Bra000001
A03	.	BED_block	8796107	8796291	0	+	.	Parent=BED_feature1;Name=Bra000001

**Comment by mfcovington** [comment]
Also, `cd` into the repo and run `prove`. What do you see?

**Comment by rjcmarkelz** [comment]
```
t/extract-utr.t .. Can't open '/Users/Cody_2/git.repos/extract-utr/t/sample-files/expect.500-5prime+full-cds.fa' for reading: 'No such file or directory' at t/extract-utr.t line 73
    # Child (5'-UTR extractions) exited without calling finalize()
t/extract-utr.t .. 1/3 
#   Failed test '5'-UTR extractions'
#   at /System/Library/Perl/5.16/Test/Builder.pm line 252.
# Looks like you planned 3 tests but ran 1.
# Looks like you failed 1 test of 1 run.
# Looks like your test exited with 29 just after 1.
t/extract-utr.t .. Dubious, test returned 29 (wstat 7424, 0x1d00)
Failed 3/3 subtests 

Test Summary Report
-------------------
t/extract-utr.t (Wstat: 7424 Tests: 1 Failed: 1)
  Failed test:  1
  Non-zero exit status: 29
  Parse errors: Bad plan.  You planned 3 tests but ran 1.
Files=1, Tests=1,  1 wallclock secs ( 0.03 usr  0.01 sys +  0.17 cusr  0.06 csys =  0.27 CPU)
Result: FAIL
```

**Comment by rjcmarkelz** [comment]
Opps on the last comment. It looks like it is trying to find a file that does not exist. Here is what I am giving as the command to run the script:

```
perl extract-utr.pl --gff_file=/Users/Cody_2/git.repos/brassica_genome_db/raw_data/Brassica_rapa_v1.5_final.gff3  --genome_fa_file=/Users/Cody_2/git.repos/brassica_genome_db/raw_data/Brassica_rapa_v1.5.fa  --cds_fa_file=/Users/Cody_2/git.repos/brassica_genome_db/raw_data/Brassica_rapa_v1.5_final.fa  --fiveprime --utr_length=1000 --gene_length=0  --output_fa_file=Brapa_1000bp_upstream.fa
```

MFC edit (so I can read t easier):

``` bash
perl extract-utr.pl \
  --gff_file=/Users/Cody_2/git.repos/brassica_genome_db/raw_data/Brassica_rapa_v1.5_final.gff3 \
  --genome_fa_file=/Users/Cody_2/git.repos/brassica_genome_db/raw_data/Brassica_rapa_v1.5.fa \
  --cds_fa_file=/Users/Cody_2/git.repos/brassica_genome_db/raw_data/Brassica_rapa_v1.5_final.fa \
  --fiveprime \
  --utr_length=1000 \
  --gene_length=0 \
  --output_fa_file=Brapa_1000bp_upstream.fa
```

**Comment by mfcovington** [comment]
Oops. That's because there are files missing from the testing folder. Let me commit them. (Doesn't affect script, just the expected output.

**Comment by mfcovington** [comment]
Commit 6af2951d8ce29e03998899b37f76ae744458634c should fix the testing problem (with `prove`).

**Comment by rjcmarkelz** [comment]
t/extract-utr.t .. ok  
All tests successful.
Files=1, Tests=3,  1 wallclock secs ( 0.03 usr  0.00 sys +  0.80 cusr  0.32 csys =  1.15 CPU)
Result: PASS

**Comment by mfcovington** [comment]
OK. Run your common w/o the `=` signs:

```
perl extract-utr.pl \
  --gff_file        /Users/Cody_2/git.repos/brassica_genome_db/raw_data/Brassica_rapa_v1.5_final.gff3 \
  --genome_fa_file  /Users/Cody_2/git.repos/brassica_genome_db/raw_data/Brassica_rapa_v1.5.fa \
  --cds_fa_file     /Users/Cody_2/git.repos/brassica_genome_db/raw_data/Brassica_rapa_v1.5_final.fa \
  --fiveprime \
  --utr_length      1000 \
  --gene_length     0 \
  --output_fa_file  Brapa_1000bp_upstream.fa
```

**Comment by rjcmarkelz** [comment]
still blank.
-rw-r--r--  1 Cody_2  staff     0B Jan 22 16:39 Brapa_1000bp_upstream.fa

**Comment by mfcovington** [comment]
What do you get for this:

```
grep -c CDS /Users/Cody_2/git.repos/brassica_genome_db/raw_data/Brassica_rapa_v1.5_final.gff3
```

**Comment by rjcmarkelz** [comment]
0
So the path is incorrect?

**Comment by rjcmarkelz** [comment]
There is 0 CDS. Let me take a look at your test files to see what might be different.

**Comment by mfcovington** [comment]
Scroll down to where it says '_Here is how this gene should be described using GFF3_' at http://www.sequenceontology.org/gff3.shtml. This is also how the ITAG GFF3 is constructed and the structure I used.

**Comment by rjcmarkelz** [comment]
This is in extract-utr.pl?

**Comment by mfcovington** [comment]
Oops. Forgot the link: http://www.sequenceontology.org/gff3.shtml

**Comment by mfcovington** [comment]
Lines 124 and 126 of the script will be important.

**Comment by rjcmarkelz** [comment]
So it looks like the conversion from bed to gff3 did not work properly, or the .bed file does not have the correct information.
Head Bed:
A03 8794389 8797343 Bra000001   0   +   8794510 8797095 0   9   145,184,82,105,388,185,106,149,540  0,232,868,1041,1244,1717,1984,2173,2414
A03 8797641 8800479 Bra000002   0   -   8797898 8800379 0   6   417,152,162,352,63,300  0,503,755,1134,1592,2538
A03 8811737 8813527 Bra000003   0   +   8812469 8813271 0   3   592,298,568 0,692,1222
A03 8816600 8817498 Bra000004   0   +   8816857 8817232 0   1   898 0
A03 8818079 8820313 Bra000005   0   -   8818080 8820123 0   3   580,78,967  0,847,1267
A03 8820620 8821103 Bra000006   0   -   8820738 8821050 0   1   483 0

Data in GFF after the long header:
A03 .   BED_feature 8794390 8797343 0   +   .   ID=BED_feature1;Name=Bra000001
A03 .   BED_block   8794390 8794534 0   +   .   Parent=BED_feature1;Name=Bra000001
A03 .   BED_thick_feature   8794511 8797095 0   +   .   Parent=BED_feature1;Name=Bra000001
A03 .   BED_block   8794622 8794805 0   +   .   Parent=BED_feature1;Name=Bra000001
A03 .   BED_block   8795258 8795339 0   +   .   Parent=BED_feature1;Name=Bra000001
A03 .   BED_block   8795431 8795535 0   +   .   Parent=BED_feature1;Name=Bra000001
A03 .   BED_block   8795634 8796021 0   +   .   Parent=BED_feature1;Name=Bra000001
A03 .   BED_block   8796107 8796291 0   +   .   Parent=BED_feature1;Name=Bra000001
A03 .   BED_block   8796374 8796479 0   +   .   Parent=BED_feature1;Name=Bra000001
A03 .   BED_block   8796563 8796711 0   +   .   Parent=BED_feature1;Name=Bra000001
A03 .   BED_block   8796804 8797343 0   +   .   Parent=BED_feature1;Name=Bra000001

**Comment by rjcmarkelz** [comment]
It looks like maybe the .bed file that upendra give me is not complete?

**Comment by rjcmarkelz** [comment]
Now I see I used the genometools convertor incorrectly.

**Comment by mfcovington** [comment]
Were you able to get the converter to give you the expected output?

**Comment by rjcmarkelz** [comment]
working on it.

**Comment by rjcmarkelz** [comment]
now it does not like the fasta file. I had to kill it. I need to head home. Will discuss this with you tomorrow.

TERMINAL OUTPUT:
[_razf_open] fail to open /Users/Cody_2/git.repos/brassica_genome_db/raw_data/Brassica_rapa_v1.5.fa
[fai_build] fail to open the FASTA file /Users/Cody_2/git.repos/brassica_genome_db/raw_data/Brassica_rapa_v1.5.fa
[fai_load] fail to open FASTA index.
Terminated: 15

EXAMPLE OUTPUT FROM SCRIPT:

> gene1
> gene10
> gene100
> gene1000
> gene10000
> gene10001
> gene10002
> gene10003
> gene10004
> gene10005
> gene10006

**Comment by mfcovington** [comment]
Have you indexed the FA file, yet?

```
samtools faidx /Users/Cody_2/git.repos/brassica_genome_db/raw_data/Brassica_rapa_v1.5.fa
```

**Comment by mfcovington** [comment]
Never mind. The index should be built automatically by the script.

**Comment by rjcmarkelz** [comment]
It is working now. I made a dumb mistake when copying all the text over from sublime text.
should be Brapa_sequence_v1.5.fa 

It is running right now. I have no idea how long it will take so I will let it run over night.

**Comment by mfcovington** [comment]
What are the permissions on the FA file?

**Comment by mfcovington** [comment]
OK, good!

**Comment by rjcmarkelz** [comment]
Thanks Mike!

**Comment by rjcmarkelz** [comment]
Just FYI: I needed to change the regex on line 126 in order for it to output the gene names correctly for this brassica data set. Something to consider if you ever try making this more general.
New:
my ($gene) = $attributes =~ /Name=(Bra.+)/;

Old:
my ($gene) = $attributes =~ /Parent=(?:mRNA:)?([^;]+)/;

**Comment by mfcovington** [comment]
Can you post an extract from the file, so I can see how it is structured?

**Comment by rjcmarkelz** [comment]
my GFF: 
###
A03 .   gene    9103927 9105020 0   -   .   ID=gene53;Name=Bra000054
A03 .   CDS 9103927 9104112 0   -   .   Parent=gene53;Name=Bra000054
A03 .   mRNA    9103927 9105020 0   -   .   Parent=gene53;Name=Bra000054
A03 .   CDS 9104201 9104319 0   -   .   Parent=gene53;Name=Bra000054
A03 .   CDS 9104391 9104472 0   -   .   Parent=gene53;Name=Bra000054
A03 .   CDS 9104556 9104842 0   -   .   Parent=gene53;Name=Bra000054
A03 .   CDS 9104981 9105020 0   -   .   Parent=gene53;Name=Bra000054

The testing GFF: 
SL2.40ch00  ITAG_eugene exon    17336   18189   .   +   0   ID=exon:Solyc00g005000.2.1.2;Parent=mRNA:Solyc00g005000.2.1;from_BOGAS=1
SL2.40ch00  ITAG_eugene CDS 17336   17940   .   +   2   ID=CDS:Solyc00g005000.2.1.2;Parent=mRNA:Solyc00g005000.2.1;from_BOGAS=1
SL2.40ch00  ITAG_eugene three_prime_UTR 17941   18189   .   +   .   ID=three_prime_UTR:Solyc00g005000.2.1.0;Parent=mRNA:Solyc00g005000.2.1;from_BOGAS=1
###
